# Site Settings
name: CodeSik의 개발 공방
title: CodeSik의 개발 공방 | Tech Blog
email: iqeq2328@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech Blog
  Web, Server, Computer Science
image: "/src/img/blog-image.png"

# blog cover
cover: "/assets/img/blog-image.png"

translations:
  text:
    new_post: "새로운 포스트"
    see_also: "이런 포스트도 있어요."
    search: "검색 하기"
    author: "공방 주인"
    share: "공유하기"
    comments: "댓글"
  button:
    read_now: "지금 읽기"
    share_on_twitter: "트위터에 공유하기"
    share_on_facebook: "페이스북에 공유하기"
  pagination:
    page: "페이지"
    of: "of"
    next_page: "다음 페이지"
    next_post: "이전 페이지"
  recommendation:
    text: "이 글은 어떠세요?"
    back_btn: "위로 가기"
  error_404:
    title: "페이지를 찾을 수 없습니다."
    message: "죄송합니다, 입력하신 페이지를 찾을 수 없습니다."
    image_alt: "404 - Page not found"
  contact:
    title: "연락하기"
    subject: "새 연락"
    submit_btn: "보내기"
    placeholders:
      name: "이름"
      email: "이메일"
      message: "메시지"
    errors:
      locale: "en"
      empty_name: "이름을 입력해야 합니다."
      empty_email: "이메일을 입력해야 합니다."
      invalid_email: "유효하지 않은 이메일입니다."
      empty_message: "메시지를 입력해야 합니다."
    after_send:
      title: "전송 완료"
      message: "메시지를 주셔서 감사합니다. 빠른 시일 내에 답장드리도록 하겠습니다."

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: CodeSik  # Be used at blog posts' author.
  first_name: Seo  # Be used at index page about me section.
  last_name: Geonsik  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpeg  # upload your avatar at directory and edit it.
  github_username: CodeSik  # Leave blank if you don't have now
  linkedin_id:
  facebook_username: profile.php?id=100004444008184
  twitter_username:
  email: iqeq2328@gmail.com
  instagram_username: sik_gn
  cv:
    https://drive.google.com/file/d/1GsOKSEg_GsUsNsnXImyunOx5a8uXU9XO/view?usp=sharing
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: "백엔드 엔지니어를 희망하는 아직은 부족한 주니어 개발자 입니다 :) \n 사용 가능 기술 스택은 Python, C++, Java, JavaScript / Spring, Android Studio, Node.js 입니다." # Describe yourself.

## carousels
index_carousel: on # index page carousel switch
blog_carousel: on  # blog page carousel switch

tags:
  - blog
  - web
  - computer
  - developer
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Category
    url: /category
  - title: Tags
    url: /tags
  - title: Contact
    url: /contact


email: iqeq2328@gmail.com
disqus_username: codesik-github-io-1
paginate: 12


# Social Media Settings
# Remove the item if you don't need it
github_username: codesik
facebook_username: profile.php?id=100004444008184
# twitter_username: twitter_username
instagram_username: sik_gn
# linkedin_username: sunmon
# medium_username: medium_username
# tistory_username: conservative-vector

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: false
side_toc: true

# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codesik.github.io" # the base hostname & protocol for your site
google_analytics: "UA-191544283-1"
language: "ko"
categories_folder: category
sent_message_url: "/contact/message-sent/"

#translate


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-last-modified-at

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# default YAML
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "CodeSik"
      category: "undefined"
      math: true
      paginate: true
      optimized_image: "/assets/img/default_imgs/blog-image.png"

  -
    scope:
      path: "_posts/Life" # an empty string here means all files in the project
      type: "posts"
    values:
      category: "Life"
      optimized_image: "/assets/img/default_imgs/thumb/til.png"
  -
    scope:
      path: "_posts/Tips" # an empty string here means all files in the project
      type: "posts"
    values:
      category: "Tips"
      optimized_image: "/assets/img/default_imgs/thumb/tips.png"


# Theme
# version: v3.1.0
