name: CodeSik의 개발 공방
title: CodeSik의 개발 공방 | Tech Blog
email: iqeq2328@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tech Blog
  Web, Server, Computer Science
tags:
  - blog
  - web
  - computer
  - developer
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Category
    url: /category
  - title: Tags
    url: /tags
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

email: iqeq2328@gmail.com
disqus_username: codesik-github-io-1
paginate: 12
